
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Isra Shafique
 */
public class timeTable extends javax.swing.JFrame {
String tableName;
    /**
     * Creates new form timeTable
     */
public void addValueTable(String day1,int i2,Statement stmt3)
{
     ResultSet rs2;  
    try {
        rs2 = stmt3.executeQuery("select day,timeslot,teacher,class,subject from "+tableName+" order by shour,smin ");
         int j=1;int i=i2;
                while(rs2.next())
                {if(rs2.getString("day").equals(day1))
                {if(i%2==0)
                    { 
                  
                           jTable2.setValueAt(rs2.getString("timeslot"),i,j);  
                           i=i+1;
                    }
                
                    if(i%2!=0){    
                        jTable2.setValueAt("<html>"+rs2.getString("teacher")+"<br>"+rs2.getString("subject")+
                                    "<br>"+rs2.getString("class")+"</html>",i,j);
                                         j=j+1;i=i-1; 
                                                }}                             
                }
    } catch (SQLException ex) {
        Logger.getLogger(timeTable.class.getName()).log(Level.SEVERE, null, ex);
    }
               
               
               
}
    public timeTable(String tbName)  {
        initComponents();
        jTable2.setRowHeight(0, 30);
        jTable2.setRowHeight(2, 30);
        jTable2.setRowHeight(4, 30);
        jTable2.setRowHeight(6, 30);
        jTable2.setRowHeight(8, 30);

        jTable2.setValueAt("Monday", 1, 0);
        jTable2.setValueAt("Tuesday", 3, 0);
        jTable2.setValueAt("Wednesday", 5, 0);
        jTable2.setValueAt("Thursday", 7, 0);
        jTable2.setValueAt("Friday", 9, 0);
        tableName=tbName;
       
    try {
           
                Class.forName("com.mysql.jdbc.Driver");
            
                int minH=-1;int ID;int minM=-1;int maxH=-1;int maxM=-1;int i=0;
                Connection con=DriverManager.getConnection(  
                "jdbc:mysql://localhost:3306/timetable?zeroDateTimeBehavior=convertToNull","root","");
               
                 Statement stmt3=con.createStatement();  
                 addValueTable("MONDAY",0,stmt3);
                 addValueTable("TUESDAY",2,stmt3);
                 addValueTable("WEDNESDAY",4,stmt3);
                 addValueTable("THURSDAY",6,stmt3);
                 addValueTable("FRIDAY",8,stmt3);

               //query of insertion
    } catch (SQLException ex) {
        Logger.getLogger(timeTable.class.getName()).log(Level.SEVERE, null, ex);
    } catch (ClassNotFoundException ex) {
        Logger.getLogger(timeTable.class.getName()).log(Level.SEVERE, null, ex);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 0));

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setBackground(new java.awt.Color(255, 255, 153));
        jTable2.setForeground(new java.awt.Color(153, 0, 0));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        jTable2.setAutoscrolls(false);
        jTable2.setGridColor(new java.awt.Color(51, 51, 51));
        jTable2.setRowHeight(65);
        jTable2.setRowMargin(20);
        jTable2.getTableHeader().setResizingAllowed(false);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setForeground(new java.awt.Color(153, 0, 0));
        jButton1.setText("<-----");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1061, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                setVisible(false);
               noOfSubjects nos=new noOfSubjects(tableName);
                nos.setVisible(true);
                
        




// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
